apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: zerossl-eab
data:
  secret: aWxQV3NRU2ZVaUZocVFiTnRrSDVNQUNTdDQ5eko1ZXAzN3VkWU9hYmxYVGJMdkFqa0Y4WmswdGhUY0dNV0x1SURkZzhXeFlZSWQ1emtacTJoYWROOXc=